apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-uploads
  namespace: spintelligence-dsm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
