export const thresholdFieldCatalog = {
    "Cotton HVI Data Entry": [
        "Variety",
        "Invoice No",
        "Invoice Date",
        "SCI",
        "Span Length (2.5%)",
        "Mic",
        "GTEX",
        "Maturity",
        "UR",
        "SFI",
        "Elongation",
        "Yellow + B",
        "Trash",
        "RD",
        "Colour Grade",
    ],
    "Fibre Data Entry": [
        "Variety",
        "Invoice No",
        "Invoice Date",
        "Cut Length",
        "Length CV",
        "Mean Denier",
        "CV per Denier",
        "Tenacity",
        "CV per Tenacity",
        "Elongation",
        "CV per Elongation",
        "Crimp (ARC/CM)",
        "Whiteness Index",
        "Spin Finish",
    ],
    "AFIS Data Entry": [
        "Variety",
        "Invoice No",
        "Invoice Date",
        "UQL",
        "L5%",
        "SFC(N)",
        "IFC %",
        "Fibre Neps Gms",
        "SFC(W)",
        "Maturity",
        "Fineness",
        "SCN (gms)",
    ],
    "Moisture Data Entry": [
        "Party Lot No",
        "Variety",
        "Party Name",
        "PR No",
        "Value 1",
        "Value 2",
        "Value 3",
        "Value 4",
        "Value 5",
        "Value 6",
        "Value 7",
        "Value 8",
        "Value 9",
        "Value 10",
        "Average",
    ],
    "Openness Data Entry": [
        "Mixing",
        "Neps +200",
        "Neps +280",
        "Neps +500",
        "Seed Coat Nep",
        "Trash",
        "Visible Foreign Matter",
        "Invisible Foreign Matter",
    ],
};

export const getThresholdFieldsForScreen = (screenName) =>
    thresholdFieldCatalog[screenName] || [];
