export const thresholdFieldCatalog = {
    // Blend fields ("Lot No.", "Blend %", "Cut Length", "Tenacity", "Elongation", "Merge No.") are
    // intentionally not listed here — Mixing's Process Parameter collects a variable number of
    // blend rows per submission, so ReportsPage.jsx generates "Blend 1 - X".."Blend N - X" columns
    // dynamically based on how many blends are actually present in the fetched rows, instead of a
    // fixed set of singular fields that would only ever show the first blend.
    "Mixing::Process Parameter": [
        "Process Parameter ID",
        "Count Name",
        "Consignee Name",
    ],
    "Mixing::Cotton HVI Data Entry": [
        "Lot No.",
        "Variety",
        "Invoice No",
        "Invoice Date",
        "SCI",
        "Span Length (2.5%)",
        "Mic",
        "GTEX",
        "Maturity",
        "UR",
        "SFI",
        "Elongation",
        "Yellow + B",
        "TrCnt",
        "TrAr",
        "TrID",
        "Invisible Loss %",
        "Trash Content %",
        "RD",
        "Colour Grade",
        "Moisture",
        "Strength",
        "Amt",
    ],
    "Mixing::Fibre Data Entry": [
        "Lot No.",
        "Variety",
        "Invoice No",
        "Invoice Date",
        "Cut Length",
        "Length CV",
        "Mean Denier",
        "CV per Denier",
        "Tenacity",
        "CV per Tenacity",
        "Elongation",
        "CV per Elongation",
        "Crimp (ARC/CM)",
        "Whiteness Index",
        "Spin Finish",
    ],
    "Mixing::AFIS Data Entry": [
        "Lot No.",
        "Variety",
        "Invoice No",
        "Invoice Date",
        "UQL",
        "L5%",
        "SFC(N)",
        "IFC %",
        "Fibre Neps Gms",
        "SFC(W)",
        "Maturity",
        "Fineness",
        "SCN/gm",
        "L(w)",
        "L(n)",
        "Total Nep Count",
    ],
    "Mixing::AFIS-6 Cotton": [
        "Lot No.",
        "Variety",
        "Invoice Date",
        "Mc. Name",
        "Blow Room",
        "Carding",
        "Breaker Drawing",
        "Finisher Drawing",
        "Comber",
        "SCP NEP Count",
        "L(W)",
        "L(W) CV",
        "SCF(W)<12.70mm",
        "UQL(w)",
        "L(n)",
        "L(n)CV",
        "SCF(n)<12.70mm",
        "5%L(n)",
    ],
    "Mixing::AFIS-6 MMF": [
        "Lot No.",
        "Variety",
        "Invoice Date",
        "Mc. Name",
        "Blow Room",
        "Carding",
        "Breaker Drawing",
        "Finisher Drawing",
        "Comber",
        "Total Nep Count / g",
        "Total Nep mean size",
        "Fiber Nep Count",
        "Fiber Nep Mean Size",
        "SC Nep Count",
        "SC Nep Mean Size",
        "L(w)",
        "L(w)CV",
        "SCF(w)<12.70mm",
        "UQL(w)",
        "L(n)",
        "L(n)CV",
        "SCF(n)<12.70mm",
        "5%L(n)",
        "Fitness Index",
        "Maturity Ratio Mat 1",
        "IFC%",
        "50%L(n)",
        "Cut Length(n)",
        "Fineness Den",
        "Fineness CV",
        "Long Fiber >45.60mm",
        "Long Fiber Count >45.60mm",
    ],
    "Blow Room::Process Parameter": [
        "Process Parameter ID",
        "Count Name",
        "Consignee Name",
        "Line Numbers",
        "Rotary Beater Speed",
        "Depth",
        "MPM Delivery Speed",
        "MPM Delivery Pascals",
        "Condensor Speed",
        "RK Feed Roll Beater",
        "RK Beater Speed",
        "Flexi to Feed Roll Beater",
        "Flexi Beater Speed",
        "Scutcher No",
        "RK MO Speed",
        "KB Speed",
        "Grid Bar",
        "Lap Weight",
        "Uniclean",
        "SRS",
        "RK Flexi",
    ],
    "Carding::Process Parameter": [
        "Entry ID",
        "Process Parameter ID",
        "Count Name",
        "Consignee Name",
        "Machine No.",
        "Lickerin Speed",
        "Cylinder Speed",
        "Flats Speed",
        "Delivery Speed",
        "Draft",
        "Tension Draft",
        "Delivery Hank",
        "Feed Roll to Lickerin",
        "Lickerin to Cylinder",
        "Cylinder to Flats",
        "Cylinder to Doffer",
        "SFL",
        "SFD",
        "Lickerin",
        "Cylinder",
        "Doffer",
        "Flats",
    ],
    "Simplex::Process Parameter": [
        "Process Parameter ID",
        "Count Name",
        "Consignee Name",
        "Machine No.",
        "Make",
        "Delivery Hank",
        "TPI / TM",
        "Speed",
        "Bottom Roller Setting",
        "Top Roller Setting",
        "Break Draft",
        "Total Draft",
        "Creel Draft",
        "Falls twister Grooves",
        "Spacer",
        "Top Arm Pressure",
        "Back Condensor",
        "Middle Condensor",
        "Front Condensor",
        "Coils/Inch",
        "Lifter Combination Wheel",
        "Lifter Wheel",
        "Tension Wheel",
    ],
    "Spinning::Process Parameter": [
        "Process Parameter ID",
        "Count Name",
        "Consignee Name",
        "Machine No.",
        "Bottom Roll Setting",
        "Top Roll Setting",
        "Break Draft",
        "Total Draft",
        "TPI / TM",
        "Spacer",
        "Traveller",
        "Speed",
        "Make",
        "Denier",
        "Mergen Number",
        "Slub Party Code",
        "Slub / Mtr",
        "Pause Min",
        "Pause Max",
        "Slub Min",
        "Slub Max",
        "Thickness Min",
        "Thickness Max",
        "Ramp",
        "Offset",
        "Lycra Draft",
        "Lycra %",
    ],
    "Autoconer::Process Parameter": [
        "Process Parameter ID",
        "Count Name",
        "Consignee Name",
        "Machine No.",
        "Drum No.",
        "Speed",
        "P Cone Identification",
        "Cone Weight",
        "Initial Winding Tension",
        "Standard Winding Tension",
        "Touch Winding Tension",
        "Release Add Tension",
        "Tension Release End Yarn Layer",
        "Tension Release Decrease Ratio",
        "Tension Release Valid Yarn Layer",
        "Splicing Setting",
        "Water On / Off",
        "Splicing Length Adjust Parameter",
        "Splicing Nozzle",
        "Cradle Pressure",
        "Cone Density",
        "Cone / Cops",
    ],
    "Process Parameter": [
        "Process Parameter ID",
        "Count Name",
        "Consignee Name",
    ],
    "Cotton HVI Data Entry": [
        "Lot No.",
        "Variety",
        "Invoice No",
        "Invoice Date",
        "SCI",
        "Span Length (2.5%)",
        "Mic",
        "GTEX",
        "Maturity",
        "UR",
        "SFI",
        "Elongation",
        "Yellow + B",
        "TrCnt",
        "TrAr",
        "TrID",
        "Invisible Loss %",
        "Trash Content %",
        "RD",
        "Colour Grade",
        "Moisture",
        "Strength",
        "Amt",
    ],
    "Fibre Data Entry": [
        "Lot No.",
        "Variety",
        "Invoice No",
        "Invoice Date",
        "Cut Length",
        "Length CV",
        "Mean Denier",
        "CV per Denier",
        "Tenacity",
        "CV per Tenacity",
        "Elongation",
        "CV per Elongation",
        "Crimp (ARC/CM)",
        "Whiteness Index",
        "Spin Finish",
    ],
    "AFIS Data Entry": [
        "Lot No.",
        "Variety",
        "Invoice No",
        "Invoice Date",
        "UQL",
        "L5%",
        "SFC(N)",
        "IFC %",
        "Fibre Neps Gms",
        "SFC(W)",
        "Maturity",
        "Fineness",
        "SCN/gm",
        "L(w)",
        "L(n)",
        "Total Nep Count",
    ],
    "AFIS-6 Cotton": [
        "Entry ID",
        "Lot No.",
        "Variety",
        "Invoice Date",
        "Mc. Name",
        "Blow Room",
        "Carding",
        "Breaker Drawing",
        "Finisher Drawing",
        "Comber",
        "SCP NEP Count",
        "L(W)",
        "L(W) CV",
        "SCF(W)<12.70mm",
        "UQL(w)",
        "L(n)",
        "L(n)CV",
        "SCF(n)<12.70mm",
        "5%L(n)",
    ],
    "AFIS-6 MMF": [
        "Entry ID",
        "Lot No.",
        "Variety",
        "Invoice Date",
        "Mc. Name",
        "Blow Room",
        "Carding",
        "Breaker Drawing",
        "Finisher Drawing",
        "Comber",
        "Total Nep Count / g",
        "Total Nep mean size",
        "Fiber Nep Count",
        "Fiber Nep Mean Size",
        "SC Nep Count",
        "SC Nep Mean Size",
        "L(w)",
        "L(w)CV",
        "SCF(w)<12.70mm",
        "UQL(w)",
        "L(n)",
        "L(n)CV",
        "SCF(n)<12.70mm",
        "5%L(n)",
        "Fitness Index",
        "Maturity Ratio Mat 1",
        "IFC%",
        "50%L(n)",
        "Cut Length(n)",
        "Fineness Den",
        "Fineness CV",
        "Long Fiber >45.60mm",
        "Long Fiber Count >45.60mm",
    ],
    "Moisture Data Entry": [
        "Party Lot No",
        "Variety",
        "Party Name",
        "PR No",
        "Value 1",
        "Value 2",
        "Value 3",
        "Value 4",
        "Value 5",
        "Value 6",
        "Value 7",
        "Value 8",
        "Value 9",
        "Value 10",
        "Average",
    ],
    "Openness Data Entry": [
        "Entry ID",
        "Target (ASV)",
        "Entries (N)",
        "B/R Line No",
        "Overall Openness %",
        "Stage",
        "Beater Type",
        "Beater Speed (RPM)",
        "Row",
        "Weight (M)",
        "Volume 1",
        "Volume 2",
        "Average Volume (V)",
        "Apparent Specific Vol (A=V/M)",
        "Actual Op. Value (AOV)",
        "Avg. Weight (M)",
        "Avg. Volume (V)",
        "Average of Apparent Specific Vol (A=V/M)",
        "Average of Actual Op. Value (AOV)",
        "Openness %",
    ],
    "Between & Within Data Entry - Within": [
        "Test ID",
        "Date",
        "MC Name",
        "Inspection Type",
        "Number of Entries",
        "Sample Weight Calculations - Avg",
        "Sample Weight Calculations - Max",
        "Sample Weight Calculations - Min",
        "Sample Weight Calculations - Range",
        "Sample Weight Calculations - SD",
        "Sample Weight Calculations - CV",
        "Hank Calculations - Avg",
        "Hank Calculations - Max",
        "Hank Calculations - Min",
        "Hank Calculations - Range",
        "Hank Calculations - SD",
        "Hank Calculations - CV",
    ],
    "Between & Within Data Entry - Between": [
        "Test ID",
        "Date",
        "MC Name",
        "Inspection Type",
        "Number of Entries",
        "Sample Weight Calculations - Avg",
        "Sample Weight Calculations - Max",
        "Sample Weight Calculations - Min",
        "Sample Weight Calculations - Range",
        "Sample Weight Calculations - SD",
        "Sample Weight Calculations - CV",
        "Hank Calculations - Avg",
        "Hank Calculations - Max",
        "Hank Calculations - Min",
        "Hank Calculations - Range",
        "Hank Calculations - SD",
        "Hank Calculations - CV",
    ],
    // Kept non-empty (even though "Entry ID" is auto-appended anyway and gets deduped) so this
    // screen's available fields don't fall back to inferring raw, ugly-titleCased column names
    // directly from the row (e.g. "Card Thick Place Cdg01") alongside the properly-labeled
    // per-machine columns generated dynamically in ReportsPage.jsx's availableFields. Left as-is
    // (ReportsPage's Custom Report screen reads this same bare key) - the Threshold Values screen
    // instead gets its own "Carding::"-scoped entry below with the real per-machine fields, since
    // it looks up fields by (sub-department, screen) and never merges in ReportsPage's dynamic
    // per-machine discovery.
    "Thick place & CV": ["Entry ID"],
    "Thick place & CV - B/R Line 11(CDG 03 &06) - Card Thick Place Value": ["card_thick_place_cdg_03", "card_thick_place_cdg_06"],
    "Thick place & CV - B/R Line 11(CDG 03 &06) - 5m CV": ["five_m_cv_cdg_03", "five_m_cv_cdg_06"],
    // cardThickPlaceEntry.jsx's default machine set is CDG-01..CDG-25 (extendable from the CDG
    // master machine list) - each machine contributes its own Card Thick Place Value/5m CV pair,
    // same per-machine shape as ReportsPage.jsx's dynamic card_thick_place_<slug>/five_m_cv_<slug>
    // columns, but listed statically here so Threshold Values has real fields to pick from instead
    // of falling back to a single "Entry ID".
    "Carding::Thick place & CV": [
        "Entry ID",
        ...Array.from({ length: 25 }, (_, i) => `CDG-${String(i + 1).padStart(2, "0")}`).flatMap((machine) => [
            `${machine} - Card Thick Place Value`,
            `${machine} - 5m CV`,
        ]),
    ],
    "Carding NRE%": [
        "Entry ID",
        "Machine Model",
        "Mc Name",
        "Cylinder Wire Specification - Specs",
        "Cylinder Wire Specification - Tonnage in Kgs (1)",
        "Cylinder Wire Specification - Tonnage in Kgs (2)",
        "Doffer Wire Specification - Specs",
        "Doffer Wire Specification - Tonnage in Kgs (1)",
        "Doffer Wire Specification - Tonnage in Kgs (2)",
        "Flat Wire Specification - Specs",
        "Flat Wire Specification - Tonnage in Kgs (1)",
        "Flat Wire Specification - Tonnage in Kgs (2)",
        "Lickerin Wire Specification - Specs",
        "Lickerin Wire Specification - Tonnage in Kgs (1)",
        "Lickerin Wire Specification - Tonnage in Kgs (2)",
        "Silver Hank",
        "Delivery Mtr / Min",
        "Fibre Nep / Gms card mat",
        "Fibre Nep / Gms in Silver",
        "Carding NRE%",
    ],
    "Individual Card performance Data": [
        "Type",
        "Carding Machine No.",
        "Entry ID",
        "Time",
        "Raw Material / Mixing",
        "Count Name",
        "Spinning Machine Name",
        "Autoconer Machine Name",
        "Product",
        "Nature of Trials/Sample",
        "Yarn Results (optional)",
        "Total Cuts",
        "Neps Cuts",
        "Short Cuts",
        "Long Cuts",
        "Thin Cuts",
        "CP",
        "CM",
        "CCP",
        "CCM",
        "JP",
        "JM",
        "A1",
        "A2",
        "A3",
        "A4",
        "B1",
        "B2",
        "B3",
        "B4",
        "C1",
        "C2",
        "C3",
        "C4",
        "D1",
        "D2",
        "D3",
        "D4",
        "E",
        "F",
        "G",
        "H1",
        "H2",
        "I1",
        "I2",
        "CVB",
        "FL CUT",
        "FD CUT",
        "User ID",
        "U%",
        "CVM",
        "CVM cv%",
        "CVM 10 mtr",
        "DR 1.5m",
        "Thin -50%",
        "Thick +50%",
        "Neps +200%",
        "Total (Regular)",
        "Thin -40%",
        "Thick +35%",
        "Neps +140%",
        "Total (HS)",
        "Thin -30%",
        "Count",
        "CSP",
        "Yarn Remarks (optional)",
        "Type (Trial/Sample)",
        "Drg Mc. No.",
        "Finish U%",
        "Draw Frame CVIM",
        "Draw Frame CVB",
        "SMX No.",
        "SPL No.",
        "Roving%",
        "Simplex CVIM",
    ],
    "Carding::Nati Data Entry": [
        "Entry ID",
        "Variety",
        // natiDataEntry.jsx's on-screen label is "Number of Neps Entries (Max 10)" (the preview
        // modal shows it as "Entry Count" instead, but that field isn't part of the per-row
        // threshold values createThresholdViolationTickets sends - only the row fields below are).
        "Number of Neps Entries (Max 10)",
        "MC No",
        "Ratio into size-1.0",
        "Ratio into size-0.7",
        "Ratio into size-0.5",
    ],
    "Comber::Nati Data Entry": [
        "Entry ID",
        "Variety",
        "Number of Neps Entries",
        "Ratio into size-1.0",
        "Ratio into size-0.7",
        "Ratio into size-0.5",
    ],
    "Nati Data Entry": [
        "Entry ID",
        "Variety",
        "Number of Neps Entries",
        "Ratio into size-1.0",
        "Ratio into size-0.7",
        "Ratio into size-0.5",
    ],
    "Carding::U% Data Entry": [
        "Entry ID",
        "Shift",
        "Variety",
        "MC No.",
        "U%",
        "CVM",
        "1mCV",
        "3 mCV",
        "Remarks",
    ],
    "Comber::U% Data Entry": [
        "Entry ID",
        "Shift",
        "Variety",
        "MC No.",
        "U%",
        "CVM",
        "1mCV",
        "3 mCV",
        "Remarks",
    ],
    "Comber NRE%": [
        "Entry ID",
        "Silver Hank",
        "Delivery Mtr / Min",
        "Comber Neps / Min",
        "Feed in mm / Nep",
        "Fiber Nep in Comber Lap / Gms",
        "Fiber Nep / Gms in Silver",
        "Comber NRE%",
    ],
    "Comber Efficiency": [
        "Entry ID",
        "Mc Name",
        "50% span length in LAP",
        "50% span length in Sliver",
        "Combing Efficiency",
    ],
    "Comber Nolis %": [
        "Entry ID",
        "Test ID",
        "Machine ID",
        "Total Test",
        "Number of Entries (N)",
        "Tester",
        "Std. Noils %",
        "Noils %",
        "Sample No",
        "Sliver Wt",
        "Noils Wt",
        "Label",
    ],
    "U% Data Entry": [
        "Entry ID",
        "Shift",
        "Variety",
        "MC No.",
        "U%",
        "CVM",
        "1mCV",
        "3 mCV",
        "Remarks",
    ],
    "Card DFK Data": [
        "Entry ID",
        "Machine Name",
        "DFK",
        "CCD",
        "ICFD (1)",
        "LT",
        "CDS",
        "SILVER DRAFT",
        "ICFD (2)",
        "IDF IN",
        "IDF OUT",
        "AL ON",
    ],
    // spinning.js's checking form never renders/collects an "Inspection Date" field for this
    // type (no date input, and previewItems/createThresholdViolationTickets' values never include
    // one) - dropped so Threshold Values doesn't offer a field that can never carry a real value.
    "COTS Checking": [
        "Machine No.",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Count Change": [
        "Entry ID",
        "RF No.",
        "Lycra Draft",
        "Count Name (From)",
        "Count Name (To)",
        "No. of Readings",
        "Avg Reading",
        "Avg Count",
        "Avg Strength",
        "Overall CSP",
        "Count CV %",
        "Strength CV %",
        // Per-reading "Reading N - Reading No./Reading Value/Count/Count CV %/Strength/Strength CV%/CSP"
        // columns (as many as the highest reading count seen across loaded rows) are generated
        // dynamically in ReportsPage.jsx, same pattern as BR Waste Study/Drop Test's per-row columns.
    ],
    // Matches spinning.js's isRingFrame summary fields (bodyItems built in handleSaveRecord) -
    // Entry ID/Shift/Checker Name/.../Comments below are what actually reaches previewItems and
    // therefore createThresholdViolationTickets' values array. The per-machine row fields (Lycra,
    // Bobbin Color, positions 1-6, Guide Roll Lapping, Others, Total) live only in the "Ring Frame
    // Rows" previewGroups table, keyed per machine picked from a dynamic, unbounded machine-master
    // list (ringFrameMachineOptions) - not a fixed set enumerable here, and not included in the
    // values threshold tickets are actually created from, so (like Count Change's per-reading
    // columns above) they're intentionally left out of this static catalog.
    "Ring Frame Log Book": [
        "Entry ID",
        "Shift",
        "Checker Name",
        "Out of Center AC",
        "Out of Center RF",
        "Fault Cops AC",
        "Fault Cops RF",
        "Total Cops AC",
        "Total Cops RF",
        "Grand Total",
        "Guide Roll",
        "Lycra Missing",
        "Others",
        "Comments",
    ],
    // spinning.js's generic checking form never renders/collects an "Inspection Date" field for
    // Speed Checking or Lycra Missing (no date input, and neither previewItems nor
    // createThresholdViolationTickets' values array ever carries one) - dropped below, same fix as
    // Bottom Apron/Lycra Out of Centering/RSM checks above. Both sides' remarks textarea is also
    // labeled plainly "Remarks" on screen (not "LHS Remarks"/"RHS Remarks") - see the
    // side-header/remarks-header markup in spinning.js's comparison-box.
    "Speed Checking": [
        "Machine",
        "Display Speed",
        "Spindle Speed",
        "Difference",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "Remarks",
    ],
    // Lycra Missing doesn't set useArrayLhsRhs (only Speed Checking/COTS Checking/Type-2 screens
    // do), so it uses the single-value LHS/RHS inputs - no "Count of LHS/RHS Spindle" fields exist
    // for it, unlike Speed Checking above.
    "Lycra Missing": [
        "Machine",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Remarks",
    ],
    // spinning.js's checking form (useArrayLhsRhs branch) never renders/collects an "Inspection
    // Date" field for any of Bottom Apron/Lycra Out of Centering/RSM checks - no date input, and
    // neither previewItems nor createThresholdViolationTickets' values array ever carries one -
    // dropped from every key below so Threshold Values doesn't offer a field that can never carry
    // a real value. Each type's Type-2 dropdown (type2OptionsByType in spinning.js) also has more
    // non-"Nil" options than this file previously modeled as "- <Type-2 value>" composite keys;
    // the missing ones are added here, and the one that didn't match any real option ("Lycra out
    // of center Running") is corrected to the real options ("Both", "Lycra Not Center").
    "Bottom Apron Checking": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Bottom Apron Checking - Apron Damage": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Bottom Apron Checking - Apron Position Not Center": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Bottom Apron Checking - Apron Nil Idle": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Bottom Apron Checking - Apron Nil Running": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Lycra Out of Centering": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Lycra Out of Centering - Both": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Lycra Out of Centering - Lycra Out of Center": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Lycra Out of Centering - Lycra Not Center": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "RSM & Lycrasensor Checking Online": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "RSM & Lycrasensor Checking Online - RSM Not Working": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "RSM & Lycrasensor Checking Online - RSM Half Open": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "RSM & Lycrasensor Checking Online - RSM Working but Roving Run": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "RSM & Lycrasensor Checking Online - Cable Problem": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "RSM & Lycrasensor Checking Online - Lycrasensor Not Working": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "RSM & Lycrasensor Checking Offline": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "RSM & Lycrasensor Checking Offline - RSM Not Working": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "RSM & Lycrasensor Checking Offline - RSM Half Open": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "RSM & Lycrasensor Checking Offline - RSM Working but Roving Run": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "RSM & Lycrasensor Checking Offline - Cable Problem": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "RSM & Lycrasensor Checking Offline - Lycrasensor Not Working": [
        "Machine",
        "Type-2",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "Count of LHS Spindle",
        "Count of RHS Spindle",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Draw Frame::Wheel Change - Breaker Type 1": [
        "Checking Type",
        "Line Type",
        "Wheel Change Type",
        "Entry ID",
        "Date",
        "Machine No.",
        "Mixing",
        "Blend %",
        "Del-Hank",
        "Feed Hank",
        "No. of Ends",
        "Speed",
        "Draft Constant",
        "NW1",
        "NW2",
        "Total Draft",
        "BDCP (W4 / Break Draft)",
        "Creel Tension (W1VWW2) / Creel Tension Draft",
        "Feed Tension (W8/VEG) / Feed Tension Draft",
        "Web Tension (W3) / Web Tension Draft",
        "Trumpet",
        "Bottom Roller Setting Front Zone",
        "Bottom Roller Setting Back Zone",
    ],
    "Draw Frame::Wheel Change - Breaker Type 2": [
        "Checking Type",
        "Line Type",
        "Wheel Change Type",
        "Entry ID",
        "Date",
        "Machine No.",
        "Mixing",
        "Blend %",
        "Del-Hank",
        "Feed Hank",
        "No. of Ends",
        "Speed",
        "Total Draft (Formula)",
        "Total Draft from G1/G2 Combinations",
        "G1/G2",
        "BDCP (C4) / Break Draft",
        "Web Tension (C3) / Web Tension Draft",
        "Trumpet",
        "Bottom Roller Setting Front Zone",
        "Bottom Roller Setting Back Zone",
    ],
    "Draw Frame::Wheel Change - Breaker Type 3": [
        "Checking Type",
        "Line Type",
        "Wheel Change Type",
        "Entry ID",
        "Date",
        "Machine No.",
        "Mixing",
        "Blend %",
        "Del-Hank",
        "Feed Hank",
        "No. of Ends",
        "Speed",
        "Total Draft (Formula)",
        "Total Draft from G1/G2 Combinations",
        "G1/G2",
        "BDCP (C4) / Break Draft",
        "Web Tension (C3) / Web Tension Draft",
        "Trumpet",
        "Bottom Roller Setting Front Zone",
        "Bottom Roller Setting Back Zone",
    ],
    "Draw Frame::Wheel Change - Finisher Type 1": [
        "Checking Type",
        "Line Type",
        "Wheel Change Type",
        "Entry ID",
        "Date",
        "Machine No.",
        "Mixing",
        "Blend %",
        "Del-Hank",
        "Feed Hank",
        "No. of Ends",
        "Speed",
        "Total Draft",
        "Total Draft Constant",
        "NW1",
        "NW2",
        "Break Draft",
        "Back Roller Pulley Dia (W4)",
        "Middle Roller Pulley (VV)",
        "Creel Tension (W1) / Creel Draft",
        "Web Tension Wheel (W3) / Web Tension Draft",
        "Bottom Roller Setting Front Zone / Gauge in MM",
        "Bottom Roller Setting Back Zone / Gauge in MM",
        "Scanning Roller in mm",
        "Scanning Roller Load (kg)",
        "Sliver Funnel",
        "Web Guide Tube Dia",
        "Insert Bore Dia",
        "Trumpet",
    ],
    "Draw Frame::Wheel Change - Finisher Type 2": [
        "Checking Type",
        "Line Type",
        "Wheel Change Type",
        "Entry ID",
        "Date",
        "Machine No.",
        "Mixing",
        "Blend %",
        "Del-Hank",
        "Feed Hank",
        "No. of Ends",
        "Speed",
        "Total Draft",
        "Total Draft Constant",
        "NW1",
        "NW2",
        "Break Draft Wheel (W4) / Break Draft (VV)",
        "Creel Tension (W1) / Creel Draft",
        "Web Tension Wheel (W3) / Web Tension Draft",
        "Feed Tension wheel (W8) / Feed Tension Draft",
        "Bottom Roller Setting Front Zone",
        "Bottom Roller Setting Back Zone",
        "Scanning Roller in mm",
        "Trumpet",
    ],
    "Draw Frame::Wheel Change - Finisher Type 3": [
        "Checking Type",
        "Line Type",
        "Wheel Change Type",
        "Entry ID",
        "Date",
        "Machine No.",
        "Mixing",
        "Blend %",
        "Del-Hank",
        "Feed Hank",
        "No. of Ends",
        "Speed",
        "Total Draft",
        "Break Draft Wheel (W4) / Break Draft",
        "Creel Tension (W1) / Creel Draft",
        "Web Tension Wheel (W3) / Web Tension Draft",
        "Feed Tension Wheel (W8) / Feed Tension Draft",
        "Bottom Roller Setting Front Zone",
        "Bottom Roller Setting Back Zone",
        "Scanning Roller in mm",
        "Trumpet",
    ],
    "Draw Frame::Wheel Change - Finisher Type 4": [
        "Checking Type",
        "Line Type",
        "Wheel Change Type",
        "Entry ID",
        "Date",
        "Machine No.",
        "Mixing",
        "Blend %",
        "Del-Hank",
        "Feed Hank",
        "No. of Ends",
        "Speed",
        "Total Draft",
        "Break Draft Wheel / Break Draft",
        "Creel Tension (W1) / Creel Draft",
        "Web Tension Wheel (W3) / Web Tension Draft",
        "Feed Tension Wheel (W8) / Feed Tension Draft",
        "Bottom Roller Setting Front Zone / Gauge in MM",
        "Bottom Roller Setting Back Zone / Gauge in MM",
        "Scanning Roller in mm",
        "Trumpet",
    ],
    // Generic pre-subtype "Wheel Change" notebook name (checkingOptions id:10 in spinning.js) -
    // actual submissions are always recorded under "Wheel Change Type 1/2/3" (see
    // wheelChangeNotebookName in spinning.js), whose per-type field sets are the 3 catalog entries
    // below. This entry is the union of those 3 real on-screen field sets (spinning/WheelChange.jsx's
    // TYPE_1/2/3_PARAMETER_ROWS row.label values, the same ones its "Parameters (Existing /
    // Proposed)" preview table renders per row), given as plain field names (Existing/Proposed are
    // columns in that table, not part of the label) - not the "<Field> - Existing"/"- Proposed"
    // suffixed names this list previously had, and not the EOW/EPI/TPM/Range/Core Condition/
    // Production (Kgs)/Speed Front (RPM)/Speed (RPM) entries, which were backend column names
    // (WHEEL_CHANGE_FIELD_MAP's Type 1 target keys) that never correspond to any real on-screen
    // label.
    "Wheel Change": [
        "Entry ID",
        "Test No",
        "R/F No.",
        "Wheel Change Type",
        "Consignee Name",
        "Count From",
        "Lycra Type",
        "Lycra Draft",
        "Slub Code",
        "Ramp",
        "Offset On/Off",
        "Cop or Cone Condition",
        "Product Qty (Kgs)",
        "Roving Hank",
        "Raving Hank",
        "Back Roll Wheel",
        "Change Pinion",
        "BDW",
        "BD",
        "DCA",
        "DCB",
        "DFC",
        "DFF",
        "DC",
        "TCW",
        "TW",
        "B",
        "A",
        "D",
        "C",
        "TPI/TM",
        "Winding length in meters",
        "Ratchet Wheel",
        "Travellers No.",
        "Spacer",
        "Cop Weight",
        "Cop Weight (Grms)",
        "Speed Initial (RPM)",
        "Speed Max (RPM)",
        "Empties Colour",
        "Total Draft",
    ],
    "Wheel Change Type 1": [
        "Entry ID",
        "Test No",
        "R/F No.",
        "Wheel Change Type",
        "Consignee Name",
        "Count From",
        "Lycra Type",
        "Lycra Draft",
        "Slub Code",
        "Ramp",
        "Offset On/Off",
        "Cop or Cone Condition",
        "Product Qty (Kgs)",
        "Roving Hank",
        "BDW",
        "BD",
        "DCA",
        "DCB",
        "DFC",
        "DC",
        "TCW",
        "TW",
        "TPI/TM",
        "Travellers No.",
        "Spacer",
        "Cop Weight (Grms)",
        "Speed Initial (RPM)",
        "Speed Max (RPM)",
        "Empties Colour",
        "Total Draft",
    ],
    "Wheel Change Type 2": [
        "Entry ID",
        "Test No",
        "R/F No.",
        "Wheel Change Type",
        "Consignee Name",
        "Count From",
        "Lycra Type",
        "Lycra Draft",
        "Slub Code",
        "Ramp",
        "Offset On/Off",
        "Cop or Cone Condition",
        "Product Qty (Kgs)",
        "Raving Hank",
        "Back Roll Wheel",
        "Change Pinion",
        "BDW",
        "BD",
        "B",
        "A",
        "D",
        "C",
        "TPI/TM",
        "Winding length in meters",
        "Ratchet Wheel",
        "Travellers No.",
        "Spacer",
        "Speed Initial (RPM)",
        "Speed Max (RPM)",
        "Empties Colour",
        "Total Draft",
    ],
    "Wheel Change Type 3": [
        "Entry ID",
        "Test No",
        "R/F No.",
        "Wheel Change Type",
        "Consignee Name",
        "Count From",
        "Lycra Type",
        "Lycra Draft",
        "Slub Code",
        "Ramp",
        "Offset On/Off",
        "Cop or Cone Condition",
        "Product Qty (Kgs)",
        "Raving Hank",
        "BDW",
        "BD",
        "DCA",
        "DCB",
        "DFF",
        "DC",
        "TCW",
        "TW",
        "TPI/TM",
        "Travellers No.",
        "Spacer",
        "Cop Weight",
        "Speed Initial (RPM)",
        "Speed Max (RPM)",
        "Empties Colour",
        "Total Draft",
    ],
    WheelChange: [
        "Type",
        "Entry ID",
        "CDG No. (Existing)",
        "CDG No. (Proposed)",
        "Mixing - Existing",
        "Mixing - Proposed",
        "Blend % - Existing",
        "Blend % - Proposed",
        "Del-Hank - Existing",
        "Del-Hank - Proposed",
        "Feed Weight - Existing",
        "Feed Weight - Proposed",
        "Licker-in Speed 1 - Existing",
        "Licker-in Speed 1 - Proposed",
        "Licker-in Speed 2 - Existing",
        "Licker-in Speed 2 - Proposed",
        "Cylinder Speed - Existing",
        "Cylinder Speed - Proposed",
        "Flats Speed in mm/min - Existing",
        "Flats Speed in mm/min - Proposed",
        "Feed Plate to Licker-in - Existing",
        "Feed Plate to Licker-in - Proposed",
        "SFL - Existing",
        "SFL - Proposed",
        "SFD - Existing",
        "SFD - Proposed",
        "Cylinder to Flats - Existing",
        "Cylinder to Flats - Proposed",
        "Cylinder to Doffer - Existing",
        "Cylinder to Doffer - Proposed",
        "Web Speed Draft MW(V4) - Existing",
        "Web Speed Draft MW(V4) - Proposed",
        "LC-Wing Setting - Existing",
        "LC-Wing Setting - Proposed",
        "BR-RK Beater Speed - Existing",
        "BR-RK Beater Speed - Proposed",
        "Remarks (optional)",
    ],
    "Ribbon Lap CV1M Data Entry": [
        "Entry ID",
        "Machine Name",
        "Variety",
        "Date",
        "Lap Weight (KGs)",
        "Lap Length (Mts)",
        "Grams / Meter",
        "Number of Sample Entries",
        "Average",
        "Minimum",
        "Maximum",
        "Standard Deviation",
        "Coefficient of Variation (CV%)",
    ],
    "PP - Autoconer Q2": [
        "Entry ID",
        "Count Name",
        "Consignee Name",
        "N",
        "S",
        "L",
        "LH1",
        "LH2",
        "LH3",
        "LH4",
        "LH5",
        "LH6",
        "THT",
        "TH1",
        "TH2",
        "TH3",
        "TH4",
        "TH5",
        "TH6",
        "CP",
        "CM",
        "CCP",
        "CCM",
        "PC",
        "Fault Distance",
        "No. of Faults",
        "JP",
        "JM",
        "UP",
        "FL",
        "FLH1",
        "FLH2",
        "FLH3",
        "FLH4",
        "FD",
        "FDH1",
        "FDH2",
        "FDH3",
        "FDH4",
        "FDH5",
        "Reference Length",
        "Measurement",
        "Upper Alarm Limit",
        "Lower Alarm Limit",
        "Action",
    ],
    "PP - Autoconer Q3": [
        "Entry ID",
        "Count Name",
        "Consignee Name",
        "NSL1",
        "NSL2",
        "NSL3",
        "NSL4",
        "NSL5",
        "NSL6",
        "NSL7",
        "T1",
        "T2",
        "T3",
        "T4",
        "T5",
        "PF Sensing",
        "PF No. of Periods",
        "OC",
        "CP",
        "CM",
        "CCP1",
        "CCP2",
        "CCM1",
        "CCM2",
        "JP1",
        "JP2",
        "JP3",
        "JP4",
        "JP5",
        "JP6",
        "JP7",
        "JP Clearing",
        "JP U%",
        "JP JM",
        "FD1",
        "FD2",
        "FD3",
        "FD4",
        "FD5",
        "FD6",
        "Reference Length",
        "Suction",
        "Measurement",
        "Upper Limit",
        "Lower Limit",
        "Action",
        "Suction Status",
        "Blocking",
    ],
    "PP - Autoconer Q4": [
        "Entry ID",
        "Count Name",
        "Consignee Name",
        "NSL1",
        "NSL2",
        "NSL3",
        "NSL4",
        "NSL5",
        "NSL6",
        "NSL7",
        "T1",
        "T2",
        "T3",
        "T4",
        "T5",
        "PF Sensing",
        "PF No. of Periods",
        "OC",
        "CP",
        "CM",
        "CCP1",
        "CCP2",
        "CCM1",
        "CCM2",
        "JP1",
        "JP2",
        "JP3",
        "JP4",
        "JP5",
        "JP6",
        "JP7",
        "JP Clearing",
        "JP U%",
        "JP JM",
        "FD1",
        "FD2",
        "FD3",
        "FD4",
        "FD5",
        "FD6",
        "Reference Length",
        "Suction",
        "Measurement",
        "Upper Limit",
        "Lower Limit",
        "Action",
        "Suction",
        "Blocking",
        "X",
        "DP +30",
        "SM -30",
        "CDP1",
        "CDP2",
        "CDM1",
        "CDM2",
        "NSL Max Event",
        "T Max Event",
        "FD Max Events",
        "FL Max Events",
    ],
    "Rewinding Study": [
        "Entry ID",
        "Count Name (From)",
        "Actual Count",
        "Auto Coner No.",
        "Cone Tip",
        "No. of Cuts",
        "Break / 1 Million Meter",
        "Drum No.",
        "No. of Cones",
        "Fault Name",
        "No. of Faults",
        "% Fault",
        "Weight (Kgs)",
        "Length (meters)",
        "Total Cones",
        "Total Faults",
        "Total Weight (KGs)",
        "Total Length (M)",
        "Remarks",
    ],
    "Cone Density": [
        "Entry ID",
        "Count Name (From)",
        "Auto Coner No.",
        "Drum From/To",
        "Cone Tip",
        "Remarks (optional)",
        "Base Dia (E) (D1)",
        "Nose Dia (E) (D2)",
        "Base Dia (I) (D3)",
        "Nose Dia (I) (D4)",
        "Slant Height (B1)",
        "Vertical Height (B2)",
        "Cone Weight (Gms)",
        "Volume (Cm3)",
        "Density (Gms / Cm3)",
        "Gms / Litre",
        "W.Speed (m/Min)",
        "cN Tension",
        "Tensioner RPM",
        "Tensioner Force",
        "N Cradle Pressure",
        "Volume - Average Value",
        "Volume - Minimum Value",
        "Volume - Maximum Value",
        "Volume - Range",
        "Density - Average Value",
        "Density - Minimum Value",
        "Density - Maximum Value",
        "Density - Range",
        "Gms / Litre - Average Value",
        "Gms / Litre - Minimum Value",
        "Gms / Litre - Maximum Value",
        "Gms / Litre - Range",
    ],
    "Cone Packing Audit": [
        "Entry ID",
        "Count Name",
        "Gross Wt. (Std)",
        "Gross Wt. (Act)",
        "Box Colour",
        "Cone Colour",
        "Gum Tape Colour",
        "Count Label",
        "Cone Damage",
        "Cover Missing",
        "Cone Hardness",
        "Stap Cone",
        "Disk",
        "Barcode",
        "Center Pad",
        "Net Weight",
        "Tare Weight",
        "Strap Colour",
    ],
    "Lycra % Checking": [
        "Entry ID",
        "Lycra Draft",
        "Count Name",
        "No. of Readings",
        "Lycra Weight",
        "Fibre Weight",
        "Total Weight",
        "Lycra %",
        "Readings (Length in mm)",
    ],
    "Count Wise Cuts Record": [
        "Entry ID",
        "Machine No.",
        "Count",
        "Cone Tip",
        "Lot No.",
        "Frame No.",
        "YF",
        "YJ",
        "N",
        "S",
        "L",
        "T",
        "CP",
        "CM",
        "CCP",
        "CCM",
        "PC",
        "FD",
        "JP",
        "JM",
        "CVP",
        "A1",
        "A2",
        "A3",
        "A4",
        "B1",
        "B2",
        "B3",
        "B4",
        "C1",
        "C2",
        "C3",
        "C4",
        "D1",
        "D2",
        "D3",
        "D4",
        "E",
        "F",
        "G",
        "H1",
        "H2",
        "I1",
        "I2",
    ],
    "Splice Strength": [
        "Entry ID",
        "Test No",
        "Count Name",
        "Auto Coner No.",
        "Drum From",
        "Drum To",
        "Cone Tip",
        "CSP Value",
        "Average",
        "No. of Readings",
        "Drum No.",
        "Reading Number",
        "Splice Strength",
        "Parent Yarn Strength",
        "Percent Yarn",
    ],
    "Drum wise Appearance": [
        "Entry ID",
        "Test No",
        "Count Name",
        "Auto Coner No.",
        "Drum From",
        "Drum To",
        "Remarks",
        "Drum No.",
        "Appearance",
        // Per-drum "Drum N No." / "Drum N Appearance" columns (as many as the highest drum
        // count seen across loaded rows) are generated dynamically in ReportsPage.jsx, same
        // pattern as BR Waste Study/Card DFK Data/Thick place & CV's per-row columns.
    ],
    "CSP Parameter Entries": [
        "Entry ID",
        "Count Name",
        "Act Count",
        "Strength",
        "Count CV",
        "Strength CV",
        "CSP",
        "Cone Color",
        "U%",
        "CVM",
        "1Mtr CV",
        "3Mtr CV",
        "10Mtr CV",
        "BR 1.5mm",
        "CVB",
        "Normal IPI - Thin -50%",
        "Normal IPI - Thick +50%",
        "Normal IPI - Neps +200%",
        "Normal IPI - Total",
        "Extra Sensitive IPI - Thin -40%",
        "Extra Sensitive IPI - Thick +35%",
        "Extra Sensitive IPI - Neps +140%",
        "Extra Sensitive IPI - Total",
        "Thin -30%",
        "Neps +400%",
        "Thick +70%",
    ],
    "U% Parameter Entries": [
        "Entry ID",
        "Count Name",
        "Act Count",
        "Strength",
        "Count CV",
        "Strength CV",
        "CSP",
        "Cone Color",
        "U%",
        "CVM",
        "1Mtr CV",
        "3Mtr CV",
        "10Mtr CV",
        "BR 1.5mm",
        "CVB",
        "Normal IPI - Thin -50%",
        "Normal IPI - Thick +50%",
        "Normal IPI - Neps +200%",
        "Normal IPI - TOTAL",
        "Extra Sensitive IPI - Thin -40%",
        "Extra Sensitive IPI - Thick +35%",
        "Extra Sensitive IPI - Neps +140%",
        "Extra Sensitive IPI - TOTAL",
        "Thin -30%",
        "Neps +400%",
        "Thick +70%",
    ],
    Carding: [
      "S.No",
      "Date",
      "ID",
      "Mac Name",
      "Shift",
      "Std. Hank",
        "Avg. Hank",
        "SD",
        "CV",
        "User",
        "Remark",
    ],
    Drawing: [
      "S.No",
      "Date",
      "ID",
      "Mac Name",
      "Shift",
      "Std. Hank",
        "Avg. Hank",
        "SD",
        "CV",
        "User",
        "Remark",
    ],
    Simplex: [
      "S.No",
      "Date",
      "ID",
      "Mac Name",
      "Shift",
      "Std. Hank",
        "Avg. Hank",
        "SD",
        "CV",
        "User",
        "Remark",
    ],
    "Blow Room Sync": [
        "Line No.",
        "Variety",
        "Checked By",
        "Beater",
        "Number of Rows (N)",
        "Run Time (Seconds)",
        "Idle Time (Seconds)",
        "Sub Total Time",
        "Sync Percentage (%)",
        "Grand Total Time",
        "Total of Run Time",
        "Total of Idle Time",
        "Total of Sub Total Time",
        "Total of Sync Percentage",
    ],
    "Individual Card Waste Study": [
        "Entry ID",
        "Date",
        "Variety",
        "Carding Production (KGs)",
        "Study Type",
        "Number of Type 1 Entries",
        "Number of Type 2 Entries",
        "Number of Type 3 Entries",
        "Number of Waste Types (Max 25)",
        "Cylinder Speed",
        "Lickerin Speed",
        "Flat Speed",
        "Doffer Speed",
        "Delivery Speed",
        "Wing Setting",
        "Wing Settling 1",
        "Wing Settling 2",
        "1st Lickerin Speed",
        "2nd Lickerin Speed",
        "3rd Lickerin Speed",
        "MC No",
        "MC Production",
        "Waste Type",
        "Waste KGs Value",
        "Waste KGs %",
        "Total Waste KGs Value",
        "Total Waste KGs %",
        "Remarks",
    ],
    // The Blow Room sub-department's screen list (screenCatalog.js) names this
    // notebook "BR Waste Study Entry" (no Type suffix) even though the actual
    // data entry is always one of Type 1/2/3 below - this combined entry is
    // the union of all three Types' fields so the notebook still has a
    // non-empty field list to pick a threshold field from.
    "BR Waste Study Entry": [
        "Entry ID",
        "Date",
        "Variety",
        "Carding Production (KGs)",
        "Study Type",
        "Number of Type 1 Entries",
        "Number of Type 2 Entries",
        "Number of Type 3 Entries",
        "Number of Waste Types (Max 25)",
        "Cylinder Speed",
        "Lickerin Speed",
        "Flat Speed",
        "Doffer Speed",
        "Delivery Speed",
        "Wing Setting",
        "Wing Settling 1",
        "Wing Settling 2",
        "1st Lickerin Speed",
        "2nd Lickerin Speed",
        "3rd Lickerin Speed",
        "MC No",
        "MC Production",
        "Waste Type",
        "Waste KGs Value",
        "Waste KGs %",
        "Total Waste KGs Value",
        "Total Waste KGs %",
        "Remarks",
    ],
    "BR Waste Study Entry Type 1": [
        "Entry ID",
        "Date",
        "Variety",
        "Carding Production (KGs)",
        "Study Type",
        "Number of Type 1 Entries",
        "Number of Waste Types (Max 25)",
        "Cylinder Speed",
        "Lickerin Speed",
        "Flat Speed",
        "Doffer Speed",
        "MC No",
        "MC Production",
        "Waste Type",
        "Waste KGs Value",
        "Waste KGs %",
        "Total Waste KGs Value",
        "Total Waste KGs %",
        "Remarks",
    ],
    "BR Waste Study Entry Type 2": [
        "Entry ID",
        "Date",
        "Variety",
        "Carding Production (KGs)",
        "Study Type",
        "Number of Type 2 Entries",
        "Number of Waste Types (Max 25)",
        "Cylinder Speed",
        "Flat Speed",
        "Delivery Speed",
        "Wing Setting",
        "Lickerin Speed",
        "MC No",
        "MC Production",
        "Waste Type",
        "Waste KGs Value",
        "Waste KGs %",
        "Total Waste KGs Value",
        "Total Waste KGs %",
        "Remarks",
    ],
    "BR Waste Study Entry Type 3": [
        "Entry ID",
        "Date",
        "Variety",
        "Carding Production (KGs)",
        "Study Type",
        "Number of Type 3 Entries",
        "Number of Waste Types (Max 25)",
        "Flat Speed",
        "Delivery Speed",
        "Wing Settling 1",
        "Wing Settling 2",
        "1st Lickerin Speed",
        "2nd Lickerin Speed",
        "3rd Lickerin Speed",
        "MC No",
        "MC Production",
        "Waste Type",
        "Waste KGs Value",
        "Waste KGs %",
        "Total Waste KGs Value",
        "Total Waste KGs %",
        "Remarks",
    ],
    "Individual Card Waste Study Type 1": [
        "Entry ID",
        "Date",
        "Variety",
        "Carding Production (KGs)",
        "Study Type",
        "Number of Type 1 Entries",
        "Number of Waste Types (Max 25)",
        "Cylinder Speed",
        "Lickerin Speed",
        "Flat Speed",
        "Doffer Speed",
        "MC No",
        "MC Production",
        "Waste Type",
        "Waste KGs Value",
        "Waste KGs %",
        "Total Waste KGs Value",
        "Total Waste KGs %",
        "Remarks",
    ],
    "Individual Card Waste Study Type 2": [
        "Entry ID",
        "Date",
        "Variety",
        "Carding Production (KGs)",
        "Study Type",
        "Number of Type 2 Entries",
        "Number of Waste Types (Max 25)",
        "Cylinder Speed",
        "Flat Speed",
        "Delivery Speed",
        "Wing Setting",
        "Lickerin Speed",
        "MC No",
        "MC Production",
        "Waste Type",
        "Waste KGs Value",
        "Waste KGs %",
        "Total Waste KGs Value",
        "Total Waste KGs %",
        "Remarks",
    ],
    "Individual Card Waste Study Type 3": [
        "Entry ID",
        "Date",
        "Variety",
        "Carding Production (KGs)",
        "Study Type",
        "Number of Type 3 Entries",
        "Number of Waste Types (Max 25)",
        "Flat Speed",
        "Delivery Speed",
        "Wing Settling 1",
        "Wing Settling 2",
        "1st Lickerin Speed",
        "2nd Lickerin Speed",
        "3rd Lickerin Speed",
        "MC No",
        "MC Production",
        "Waste Type",
        "Waste KGs Value",
        "Waste KGs %",
        "Total Waste KGs Value",
        "Total Waste KGs %",
        "Remarks",
    ],
    "Drop Test Data Entry": [
        "Variety",
        "Blend",
        "No. of Tufts",
        "Tuft Variety",
        "Display Wt.",
        "Actual Wt.",
        "Average Wt.",
        "Diff (Actual Wt. - Display Wt.)",
        "Ratio (Average Wt. / Total) * 100",
    ],
    "B/R CV1M Data Entry Within Lap": [
        "Machine Name",
        "Variety",
        "Lap Weight (KGs)",
        "Lap Length (Mts)",
        "Grams / Meter",
        "Number of Sample Entries",
        "Sample No",
        "Value",
        "Average",
        "Minimum",
        "Maximum",
        "Standard Deviation",
        "CV %",
    ],
    "B/R Between Lap CV%": [
        "Machine Name",
        "Variety",
        "Lap Weight (KGs)",
        "Lap Length (Mts)",
        "Grams / Meter",
        "Number of Sample Entries",
        "Sample No",
        "Value",
        "Average",
        "Minimum",
        "Maximum",
        "Standard Deviation",
        "CV %",
    ],
    "Simplex::Wheel Change": [
        "SMX No.",
        "SMX No. (Proposed)",
        "Mixing / Process",
        "Blend",
        "Feed - Hank",
        "Delivery - Hank",
        "CP",
        "SMXID",
        "Break Draft (CP)",
        "Total Draft",
        "Front Roller Dia",
        "TW",
        "TCW [G]",
        "TCW [H]",
        "TPI",
        "TM",
        "LW",
        "LCW [E]",
        "LCW [F]",
        "Break Draft",
        "Bottom Roller Setting",
        "Top Arm Setting",
        "Top Arm Load",
        "Floating Condenser",
        "Spacer",
        "Tension",
        "Creel Draft Change (WE)",
        "Creel Draft",
        "Bobbin Colour",
        "Remarks",
    ],
    // Stretch % PDFs can OCR into any number of tables, each with any number of sample rows —
    // capped here at 4 tables x 6 samples (a practical upper bound) since Custom Report's field
    // list has to be generated ahead of time. Entries beyond this cap won't get columns.
    "Stretch %": Array.from({ length: 4 }, (_, i) => i + 1).flatMap((tableNo) => [
        `Table ${tableNo} - Test ID`,
        `Table ${tableNo} - Total Test`,
        `Table ${tableNo} - Number of Entries (N)`,
        `Table ${tableNo} - Length`,
        `Table ${tableNo} - Tester`,
        `Table ${tableNo} - Std. Stretch %`,
        `Table ${tableNo} - Stretch %`,
        `Table ${tableNo} - Remark`,
        ...Array.from({ length: 6 }, (_, i) => i + 1).flatMap((sampleNo) => [
            `Table ${tableNo} - Sample ${sampleNo} - Initial Bobbin`,
            `Table ${tableNo} - Sample ${sampleNo} - Full Bobbin`,
        ]),
        ...["Hank", "SD", "CV"].flatMap((label) => [
            `Table ${tableNo} - Summary ${label} - Initial Bobbin`,
            `Table ${tableNo} - Summary ${label} - Full Bobbin`,
        ]),
    ]),
    "SMXCots Checking Data Entry": [
        "MC Name",
        "Front Cots Damage",
        "Third Cots Damage",
        "Back Cots Damage",
        "Apron Damage",
        "Front Cots Tilting",
        "Second Cots Tilting",
        "Third Cots Tilting",
        "Back Cots Tilting",
        "Cradle Lifting",
        "Floating Condensor Missing",
        "Middle Condensor Missing",
        "Back Condensor Missing",
        "Others 1",
        "Others 2",
    ],
    "SMX Breaks Study Report": [
        "Simplex No.",
        "Start Time",
        "End Time",
        "Total Minutes",
        "TPI",
        "TPM",
        "Start HK",
        "Finish HK",
        "Average Speed",
        "Hank",
        "Mixing",
        "Roving HK",
        "Doff Length",
        "RH%",
        "TEMP%",
        "Total Spindles",
        "Running Spindles",
        "Idle Spindles",
        "Sider Name",
        // One item per filled length-row x break-column cell, labeled to match
        // getFullPreviewItems in SMXBreaksStudyReport.jsx exactly: "<length range> -
        // <break column>" using the same breakRows/breakColumns text (dashes spaced,
        // no "Length " prefix).
        ...[
            "0 - 200", "201 - 400", "401 - 600", "601 - 800", "801 - 1000", "1001 - 1200", "1201 - 1400",
            "1401 - 1600", "1601 - 1800", "1801 - 2000", "2001 - 2200", "2201 - 2400", "2401 - 2600",
        ].flatMap((lengthRange) => [
            "Roving Breaks at Finger",
            "Roving Breaks at Front Roller Nip",
            "Roving Breaks at Between Flyer",
            "Undraft",
            "Top Roller Lapping",
            "Bottom Roller Lapping",
            "SLIVER BREAKS",
            "Can Exhaust",
            "Unknown Stop",
        ].map((columnLabel) => `${lengthRange} - ${columnLabel}`)),
        "Total Breaks - Roving Breaks at Finger",
        "Total Breaks - Roving Breaks at Front Roller Nip",
        "Total Breaks - Roving Breaks at Between Flyer",
        "Total Breaks - Undraft",
        "Total Breaks - Top Roller Lapping",
        "Total Breaks - Bottom Roller Lapping",
        "Total Breaks - SLIVER BREAKS",
        "Total Breaks - Can Exhaust",
        "Total Breaks - Unknown Stop",
        "Total Breaks (Grand)",
        "Breaks % - Roving Breaks at Finger",
        "Breaks % - Roving Breaks at Front Roller Nip",
        "Breaks % - Roving Breaks at Between Flyer",
        "Breaks % - Undraft",
        "Breaks % - Top Roller Lapping",
        "Breaks % - Bottom Roller Lapping",
        "Breaks % - SLIVER BREAKS",
        "TOTAL BREAK (%) - Roving Breaks at Finger",
        "TOTAL BREAK (%) - Roving Breaks at Front Roller Nip",
        "TOTAL BREAK (%) - Roving Breaks at Between Flyer",
        "TOTAL BREAK (%) - Undraft",
        "TOTAL BREAK (%) - Top Roller Lapping",
        "TOTAL BREAK (%) - Bottom Roller Lapping",
        "TOTAL BREAK (%) - SLIVER BREAKS",
        "TOTAL BREAK (%) - Can Exhaust",
        "TOTAL BREAK (%) - Unknown Stop",
        "Total No. of Breaks/100SH",
    ],
    "1 Yard / Half Yard CV Entry": [
        "Type",
        "Entry ID",
        "Date",
        "Machine Number",
        "Remarks",
        "Number of Readings (N)",
        "S.No",
        "1 Yard Reading",
        "1/2 Yard Reading",
        "AVG (1 Yard)",
        "HANK (1 Yard)",
        "SD (1 Yard)",
        "CV% (1 Yard)",
        "AVG (1/2 Yard)",
        "HANK (1/2 Yard)",
        "SD (1/2 Yard)",
        "CV% (1/2 Yard)",
    ],
    "Draw Frame Cots Data Entry - Breaker": [
        "Type",
        "Entry ID",
        "Date",
        "Shift",
        "Process Type",
        "Fan Waste",
        "Cot Change",
        "Stripper Waste",
    ],
    "Draw Frame Cots Data Entry - Finisher": [
        "Type",
        "Entry ID",
        "Date",
        "Shift",
        "Process Type",
        "Fan Waste",
        "Cot Change",
        "Stripper Waste",
        "Auto Leveller",
        "Sliver Monitor",
        "Mass Thick Place",
        "Scanning Roller Area",
    ],
    "PP - Breaker Drawing": [
        "Type",
        "Count Name",
        "Consignee Name",
        "Entry ID",
        "Make",
        "No. of Ends",
        "Bottom Roll Setting",
        "Break Draft",
        "Total Draft",
        "Hank",
        "Web Tension Draft",
        "Trumpet Size",
        "Delivery Speed",
        "Pressure Bar",
    ],
    "PP - Finisher Drawing": [
        "Type",
        "Count Name",
        "Consignee Name",
        "Entry ID",
        "Make",
        "No. of Ends",
        "Bottom Roll Setting",
        "Break Draft",
        "Total Draft",
        "Web Tension Draft",
        "Trumpet Size",
        "Insert Size",
        "Web Funnel Size",
        "Delivery hank",
        "Delivery Speed",
        "Pressure Bar",
        "Scanning Roll Size",
    ],
    "A%": [
        "Report",
        "Test ID",
        "Machine",
        "Count System",
        "Length Unit",
        "Length",
        "Total Test",
        "Standard A%",
        "A% (N-1)",
        "A% (N+1)",
        "Date",
        "Tester",
        "Shift",
        "Process",
        "Remark",
        ...Array.from({ length: 10 }, (_, i) => i + 1).flatMap((sampleNo) => [
            `Sample ${sampleNo} - N-1`,
            `Sample ${sampleNo} - N`,
            `Sample ${sampleNo} - N+1`,
        ]),
        ...["Average Weight", "Weight (Max)", "Weight (Min)", "Range", "Hank", "SD", "CV"].flatMap((label) => [
            `${label} - N-1`,
            `${label} - N`,
            `${label} - N+1`,
        ]),
    ],
};

export const getThresholdFieldsForScreen = (screenName, context) => {
    if (context && thresholdFieldCatalog[`${context}::${screenName}`]) {
        return thresholdFieldCatalog[`${context}::${screenName}`];
    }
    return thresholdFieldCatalog[screenName] || [];
};
